version: '2.0'

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: ${PROJECT_NAME}_mysql
    restart: always
    volumes:
      - ./../db/migrations:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    networks:
      internal_net:
        ipv4_address: 172.26.5.3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_pma
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
    restart: always
    ports:
      - ${PMA_EXT_PORT}:80

  php:
    container_name: ${PROJECT_NAME}_fpm
    image: zaek_php
    volumes:
      - "./../:/home/zusic"
    networks:
      internal_net:
        ipv4_address: 172.26.5.2

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:latest
    ports:
      - ${NGINX_EXT_PORT}:80
    volumes:
      - "./../:/home/zusic"
      - ./nginx.conf:/etc/nginx/conf.d/site.conf
    networks:
      internal_net:
        ipv4_address: 172.26.5.1

#  memcached:
#    container_name: ${PROJECT_NAME}_mc
#    image: memcached:latest
#
#  redis:
#    container_name: ${PROJECT_NAME}_redis
#    image: redis:latest

networks:
  internal_net:
    ipam:
      config:
        - subnet: 172.26.0.0/16
          ip_range: 172.26.5.0/24
          gateway: 172.26.5.254